/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOfficial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOfficial{}

// UpdateOfficial struct for UpdateOfficial
type UpdateOfficial struct {
	Data UpdateOfficialData `json:"data"`
}

type _UpdateOfficial UpdateOfficial

// NewUpdateOfficial instantiates a new UpdateOfficial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOfficial(data UpdateOfficialData) *UpdateOfficial {
	this := UpdateOfficial{}
	this.Data = data
	return &this
}

// NewUpdateOfficialWithDefaults instantiates a new UpdateOfficial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOfficialWithDefaults() *UpdateOfficial {
	this := UpdateOfficial{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOfficial) GetData() UpdateOfficialData {
	if o == nil {
		var ret UpdateOfficialData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOfficial) GetDataOk() (*UpdateOfficialData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOfficial) SetData(v UpdateOfficialData) {
	o.Data = v
}

func (o UpdateOfficial) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOfficial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOfficial) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOfficial := _UpdateOfficial{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOfficial)

	if err != nil {
		return err
	}

	*o = UpdateOfficial(varUpdateOfficial)

	return err
}

type NullableUpdateOfficial struct {
	value *UpdateOfficial
	isSet bool
}

func (v NullableUpdateOfficial) Get() *UpdateOfficial {
	return v.value
}

func (v *NullableUpdateOfficial) Set(val *UpdateOfficial) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOfficial) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOfficial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOfficial(val *UpdateOfficial) *NullableUpdateOfficial {
	return &NullableUpdateOfficial{value: val, isSet: true}
}

func (v NullableUpdateOfficial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOfficial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


