/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateOfficialData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOfficialData{}

// UpdateOfficialData struct for UpdateOfficialData
type UpdateOfficialData struct {
	// user id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateOfficialDataAttributes `json:"attributes"`
}

type _UpdateOfficialData UpdateOfficialData

// NewUpdateOfficialData instantiates a new UpdateOfficialData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOfficialData(id uuid.UUID, type_ string, attributes UpdateOfficialDataAttributes) *UpdateOfficialData {
	this := UpdateOfficialData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateOfficialDataWithDefaults instantiates a new UpdateOfficialData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOfficialDataWithDefaults() *UpdateOfficialData {
	this := UpdateOfficialData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateOfficialData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateOfficialData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateOfficialData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateOfficialData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateOfficialData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateOfficialData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateOfficialData) GetAttributes() UpdateOfficialDataAttributes {
	if o == nil {
		var ret UpdateOfficialDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateOfficialData) GetAttributesOk() (*UpdateOfficialDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateOfficialData) SetAttributes(v UpdateOfficialDataAttributes) {
	o.Attributes = v
}

func (o UpdateOfficialData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOfficialData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateOfficialData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOfficialData := _UpdateOfficialData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOfficialData)

	if err != nil {
		return err
	}

	*o = UpdateOfficialData(varUpdateOfficialData)

	return err
}

type NullableUpdateOfficialData struct {
	value *UpdateOfficialData
	isSet bool
}

func (v NullableUpdateOfficialData) Get() *UpdateOfficialData {
	return v.value
}

func (v *NullableUpdateOfficialData) Set(val *UpdateOfficialData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOfficialData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOfficialData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOfficialData(val *UpdateOfficialData) *NullableUpdateOfficialData {
	return &NullableUpdateOfficialData{value: val, isSet: true}
}

func (v NullableUpdateOfficialData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOfficialData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


