/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateBirthDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBirthDate{}

// UpdateBirthDate struct for UpdateBirthDate
type UpdateBirthDate struct {
	Data UpdateBirthDateData `json:"data"`
}

type _UpdateBirthDate UpdateBirthDate

// NewUpdateBirthDate instantiates a new UpdateBirthDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBirthDate(data UpdateBirthDateData) *UpdateBirthDate {
	this := UpdateBirthDate{}
	this.Data = data
	return &this
}

// NewUpdateBirthDateWithDefaults instantiates a new UpdateBirthDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBirthDateWithDefaults() *UpdateBirthDate {
	this := UpdateBirthDate{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateBirthDate) GetData() UpdateBirthDateData {
	if o == nil {
		var ret UpdateBirthDateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateBirthDate) GetDataOk() (*UpdateBirthDateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateBirthDate) SetData(v UpdateBirthDateData) {
	o.Data = v
}

func (o UpdateBirthDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBirthDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateBirthDate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateBirthDate := _UpdateBirthDate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateBirthDate)

	if err != nil {
		return err
	}

	*o = UpdateBirthDate(varUpdateBirthDate)

	return err
}

type NullableUpdateBirthDate struct {
	value *UpdateBirthDate
	isSet bool
}

func (v NullableUpdateBirthDate) Get() *UpdateBirthDate {
	return v.value
}

func (v *NullableUpdateBirthDate) Set(val *UpdateBirthDate) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBirthDate) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBirthDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBirthDate(val *UpdateBirthDate) *NullableUpdateBirthDate {
	return &NullableUpdateBirthDate{value: val, isSet: true}
}

func (v NullableUpdateBirthDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBirthDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


