/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOfficialDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOfficialDataAttributes{}

// UpdateOfficialDataAttributes struct for UpdateOfficialDataAttributes
type UpdateOfficialDataAttributes struct {
	// official
	Official bool `json:"official"`
}

type _UpdateOfficialDataAttributes UpdateOfficialDataAttributes

// NewUpdateOfficialDataAttributes instantiates a new UpdateOfficialDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOfficialDataAttributes(official bool) *UpdateOfficialDataAttributes {
	this := UpdateOfficialDataAttributes{}
	this.Official = official
	return &this
}

// NewUpdateOfficialDataAttributesWithDefaults instantiates a new UpdateOfficialDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOfficialDataAttributesWithDefaults() *UpdateOfficialDataAttributes {
	this := UpdateOfficialDataAttributes{}
	return &this
}

// GetOfficial returns the Official field value
func (o *UpdateOfficialDataAttributes) GetOfficial() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Official
}

// GetOfficialOk returns a tuple with the Official field value
// and a boolean to check if the value has been set.
func (o *UpdateOfficialDataAttributes) GetOfficialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Official, true
}

// SetOfficial sets field value
func (o *UpdateOfficialDataAttributes) SetOfficial(v bool) {
	o.Official = v
}

func (o UpdateOfficialDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOfficialDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["official"] = o.Official
	return toSerialize, nil
}

func (o *UpdateOfficialDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"official",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOfficialDataAttributes := _UpdateOfficialDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOfficialDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateOfficialDataAttributes(varUpdateOfficialDataAttributes)

	return err
}

type NullableUpdateOfficialDataAttributes struct {
	value *UpdateOfficialDataAttributes
	isSet bool
}

func (v NullableUpdateOfficialDataAttributes) Get() *UpdateOfficialDataAttributes {
	return v.value
}

func (v *NullableUpdateOfficialDataAttributes) Set(val *UpdateOfficialDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOfficialDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOfficialDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOfficialDataAttributes(val *UpdateOfficialDataAttributes) *NullableUpdateOfficialDataAttributes {
	return &NullableUpdateOfficialDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateOfficialDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOfficialDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


