/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateBirthDateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBirthDateData{}

// UpdateBirthDateData struct for UpdateBirthDateData
type UpdateBirthDateData struct {
	// user id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateBirthDateDataAttributes `json:"attributes"`
}

type _UpdateBirthDateData UpdateBirthDateData

// NewUpdateBirthDateData instantiates a new UpdateBirthDateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBirthDateData(id uuid.UUID, type_ string, attributes UpdateBirthDateDataAttributes) *UpdateBirthDateData {
	this := UpdateBirthDateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateBirthDateDataWithDefaults instantiates a new UpdateBirthDateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBirthDateDataWithDefaults() *UpdateBirthDateData {
	this := UpdateBirthDateData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateBirthDateData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateBirthDateData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateBirthDateData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateBirthDateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateBirthDateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateBirthDateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateBirthDateData) GetAttributes() UpdateBirthDateDataAttributes {
	if o == nil {
		var ret UpdateBirthDateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateBirthDateData) GetAttributesOk() (*UpdateBirthDateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateBirthDateData) SetAttributes(v UpdateBirthDateDataAttributes) {
	o.Attributes = v
}

func (o UpdateBirthDateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBirthDateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateBirthDateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateBirthDateData := _UpdateBirthDateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateBirthDateData)

	if err != nil {
		return err
	}

	*o = UpdateBirthDateData(varUpdateBirthDateData)

	return err
}

type NullableUpdateBirthDateData struct {
	value *UpdateBirthDateData
	isSet bool
}

func (v NullableUpdateBirthDateData) Get() *UpdateBirthDateData {
	return v.value
}

func (v *NullableUpdateBirthDateData) Set(val *UpdateBirthDateData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBirthDateData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBirthDateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBirthDateData(val *UpdateBirthDateData) *NullableUpdateBirthDateData {
	return &NullableUpdateBirthDateData{value: val, isSet: true}
}

func (v NullableUpdateBirthDateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBirthDateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


