/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSexDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSexDataAttributes{}

// UpdateSexDataAttributes struct for UpdateSexDataAttributes
type UpdateSexDataAttributes struct {
	// sex
	Sex string `json:"sex"`
}

type _UpdateSexDataAttributes UpdateSexDataAttributes

// NewUpdateSexDataAttributes instantiates a new UpdateSexDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSexDataAttributes(sex string) *UpdateSexDataAttributes {
	this := UpdateSexDataAttributes{}
	this.Sex = sex
	return &this
}

// NewUpdateSexDataAttributesWithDefaults instantiates a new UpdateSexDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSexDataAttributesWithDefaults() *UpdateSexDataAttributes {
	this := UpdateSexDataAttributes{}
	return &this
}

// GetSex returns the Sex field value
func (o *UpdateSexDataAttributes) GetSex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sex
}

// GetSexOk returns a tuple with the Sex field value
// and a boolean to check if the value has been set.
func (o *UpdateSexDataAttributes) GetSexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sex, true
}

// SetSex sets field value
func (o *UpdateSexDataAttributes) SetSex(v string) {
	o.Sex = v
}

func (o UpdateSexDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSexDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sex"] = o.Sex
	return toSerialize, nil
}

func (o *UpdateSexDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sex",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSexDataAttributes := _UpdateSexDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSexDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateSexDataAttributes(varUpdateSexDataAttributes)

	return err
}

type NullableUpdateSexDataAttributes struct {
	value *UpdateSexDataAttributes
	isSet bool
}

func (v NullableUpdateSexDataAttributes) Get() *UpdateSexDataAttributes {
	return v.value
}

func (v *NullableUpdateSexDataAttributes) Set(val *UpdateSexDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSexDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSexDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSexDataAttributes(val *UpdateSexDataAttributes) *NullableUpdateSexDataAttributes {
	return &NullableUpdateSexDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateSexDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSexDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


