/*
Chains lab profile service

profile service docs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSex{}

// UpdateSex struct for UpdateSex
type UpdateSex struct {
	Data UpdateSexData `json:"data"`
}

type _UpdateSex UpdateSex

// NewUpdateSex instantiates a new UpdateSex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSex(data UpdateSexData) *UpdateSex {
	this := UpdateSex{}
	this.Data = data
	return &this
}

// NewUpdateSexWithDefaults instantiates a new UpdateSex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSexWithDefaults() *UpdateSex {
	this := UpdateSex{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateSex) GetData() UpdateSexData {
	if o == nil {
		var ret UpdateSexData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateSex) GetDataOk() (*UpdateSexData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateSex) SetData(v UpdateSexData) {
	o.Data = v
}

func (o UpdateSex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateSex) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSex := _UpdateSex{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSex)

	if err != nil {
		return err
	}

	*o = UpdateSex(varUpdateSex)

	return err
}

type NullableUpdateSex struct {
	value *UpdateSex
	isSet bool
}

func (v NullableUpdateSex) Get() *UpdateSex {
	return v.value
}

func (v *NullableUpdateSex) Set(val *UpdateSex) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSex) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSex(val *UpdateSex) *NullableUpdateSex {
	return &NullableUpdateSex{value: val, isSet: true}
}

func (v NullableUpdateSex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


