openapi: 3.0.0
info:
  description: profile service docs
  title: Chains lab profile service
  version: 0.0.1
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    CreateProfile:
      properties:
        data:
          $ref: '#/components/schemas/CreateProfile_data'
      required:
      - data
      type: object
    UpdateProfile:
      properties:
        data:
          $ref: '#/components/schemas/UpdateProfile_data'
      required:
      - data
      type: object
    UpdateUsername:
      properties:
        data:
          $ref: '#/components/schemas/CreateProfile_data'
      required:
      - data
      type: object
    UpdateBirthDate:
      properties:
        data:
          $ref: '#/components/schemas/UpdateBirthDate_data'
      required:
      - data
      type: object
    UpdateSex:
      properties:
        data:
          $ref: '#/components/schemas/UpdateSex_data'
      required:
      - data
      type: object
    UpdateOfficial:
      properties:
        data:
          $ref: '#/components/schemas/UpdateOfficial_data'
      required:
      - data
      type: object
    Profile:
      properties:
        data:
          $ref: '#/components/schemas/ProfileData'
      required:
      - data
      type: object
    ProfileData:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/ProfileAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    ProfileAttributes:
      properties:
        username:
          description: Username
          type: string
        pseudonym:
          description: Pseudonym
          type: string
        description:
          description: Description
          type: string
        avatar:
          description: Avatar URL
          format: uri
          type: string
        official:
          description: Is Official Account
          type: boolean
        sex:
          description: sex prikin'
          type: string
        birthdate:
          description: Birthday
          format: date-time
          type: string
        updated_at:
          description: Updated At
          format: date-time
          type: string
        created_at:
          description: Created At
          format: date-time
          type: string
      required:
      - created_at
      - official
      - updated_at
      - username
      type: object
    ProfilesCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/ProfileData'
          type: array
        links:
          $ref: '#/components/schemas/ProfilesCollection_links'
      required:
      - data
      - links
      type: object
    CreateProfile_data_attributes:
      properties:
        username:
          description: Username
          type: string
      required:
      - username
      type: object
    CreateProfile_data:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/CreateProfile_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateProfile_data_attributes:
      properties:
        pseudonym:
          description: Pseudonym
          type: string
        description:
          description: Description
          type: string
        avatar:
          description: Avatar URL
          format: uri
          type: string
        sex:
          description: sex prikin'
          type: string
        birthdate:
          description: Birthday
          format: date-time
          type: string
      type: object
    UpdateProfile_data:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateProfile_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateBirthDate_data_attributes:
      properties:
        birth_date:
          description: birth date user
          format: date-time
          pattern: DD-MM-YYYY
          type: string
      required:
      - birth_date
      type: object
    UpdateBirthDate_data:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateBirthDate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateSex_data_attributes:
      properties:
        sex:
          description: sex
          type: string
      required:
      - sex
      type: object
    UpdateSex_data:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateSex_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateOfficial_data_attributes:
      properties:
        official:
          description: official
          type: boolean
      required:
      - official
      type: object
    UpdateOfficial_data:
      properties:
        id:
          description: user id
          format: uuid
          type: string
        type:
          enum:
          - profile
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateOfficial_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    ProfilesCollection_links:
      properties:
        page_number:
          description: The current page number.
          example: 1
          format: int64
          type: integer
        page_size:
          description: The number of items per page.
          example: 10
          format: int64
          type: integer
        total_items:
          description: The total number of items available.
          example: 100
          format: int64
          type: integer
      required:
      - page_number
      - page_size
      - total_items
      type: object
