// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_events.sql

package pgdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createInboxEvent = `-- name: CreateInboxEvent :one
INSERT INTO inbox_events (
    topic, event_type, event_version, key, payload
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, topic, event_type, event_version, key, payload, status, attempts, next_retry_at, created_at, processed_at
`

type CreateInboxEventParams struct {
	Topic        string
	EventType    string
	EventVersion int32
	Key          string
	Payload      json.RawMessage
}

func (q *Queries) CreateInboxEvent(ctx context.Context, arg CreateInboxEventParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createInboxEvent,
		arg.Topic,
		arg.EventType,
		arg.EventVersion,
		arg.Key,
		arg.Payload,
	)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.EventType,
		&i.EventVersion,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const delayInboxEvents = `-- name: DelayInboxEvents :exec
UPDATE inbox_events
SET attempts = attempts + 1,
    next_retry_at = $2
WHERE id = ANY($1::uuid[])
`

type DelayInboxEventsParams struct {
	Column1     []uuid.UUID
	NextRetryAt time.Time
}

func (q *Queries) DelayInboxEvents(ctx context.Context, arg DelayInboxEventsParams) error {
	_, err := q.db.ExecContext(ctx, delayInboxEvents, pq.Array(arg.Column1), arg.NextRetryAt)
	return err
}

const getPendingInboxEvents = `-- name: GetPendingInboxEvents :many
SELECT id, topic, event_type, event_version, key, payload, status, attempts, next_retry_at, created_at, processed_at FROM inbox_events
WHERE status = 'pending' AND next_retry_at <= (now() AT TIME ZONE 'UTC')
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingInboxEvents(ctx context.Context, limit int32) ([]InboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxEvent
	for rows.Next() {
		var i InboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.EventType,
			&i.EventVersion,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxEventsProcessed = `-- name: MarkInboxEventsProcessed :exec
UPDATE inbox_events
SET status = 'processed',
    processed_at = $2
WHERE id = ANY($1::uuid[])
`

type MarkInboxEventsProcessedParams struct {
	Column1     []uuid.UUID
	ProcessedAt sql.NullTime
}

func (q *Queries) MarkInboxEventsProcessed(ctx context.Context, arg MarkInboxEventsProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markInboxEventsProcessed, pq.Array(arg.Column1), arg.ProcessedAt)
	return err
}
