// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package pgdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (account_id, username)
VALUES ($1, $2)
RETURNING account_id, username, official, pseudonym, description, avatar, created_at, updated_at
`

type CreateProfileParams struct {
	AccountID uuid.UUID
	Username  string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.AccountID, arg.Username)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE account_id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, accountID)
	return err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT account_id, username, official, pseudonym, description, avatar, created_at, updated_at FROM profiles
WHERE account_id = $1
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByAccountID, accountID)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT account_id, username, official, pseudonym, description, avatar, created_at, updated_at FROM profiles
WHERE username = $1
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfilesByPseudonym = `-- name: ListProfilesByPseudonym :many
SELECT account_id, username, official, pseudonym, description, avatar, created_at, updated_at FROM profiles
WHERE
    ($1::text = '' OR pseudonym ILIKE ('%' || $2::text || '%'))
    LIMIT $4::int
OFFSET $3::int
`

type ListProfilesByPseudonymParams struct {
	Prefix string
	Q      string
	Offset int32
	Limit  int32
}

func (q *Queries) ListProfilesByPseudonym(ctx context.Context, arg ListProfilesByPseudonymParams) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesByPseudonym,
		arg.Prefix,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.AccountID,
			&i.Username,
			&i.Official,
			&i.Pseudonym,
			&i.Description,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByUsername = `-- name: ListProfilesByUsername :many
SELECT account_id, username, official, pseudonym, description, avatar, created_at, updated_at FROM profiles
WHERE
    ($1::text = '' OR username ILIKE ('%' || $2::text || '%'))
    LIMIT $4::int
OFFSET $3::int
`

type ListProfilesByUsernameParams struct {
	Prefix string
	Q      string
	Offset int32
	Limit  int32
}

func (q *Queries) ListProfilesByUsername(ctx context.Context, arg ListProfilesByUsernameParams) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesByUsername,
		arg.Prefix,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.AccountID,
			&i.Username,
			&i.Official,
			&i.Pseudonym,
			&i.Description,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    pseudonym = CASE
        WHEN $2 IS NULL THEN pseudonym
        WHEN $2 = ''    THEN NULL
        ELSE $2
    END,
    description = CASE
        WHEN $3 IS NULL THEN description
        WHEN $3 = ''    THEN NULL
        ELSE $3
    END,
    avatar = CASE
        WHEN $4 IS NULL THEN avatar
        WHEN $4 = ''    THEN NULL
        ELSE $4
    END,
    updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, official, pseudonym, description, avatar, created_at, updated_at
`

type UpdateProfileParams struct {
	AccountID   uuid.UUID
	Pseudonym   sql.NullString
	Description sql.NullString
	Avatar      sql.NullString
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.AccountID,
		arg.Pseudonym,
		arg.Description,
		arg.Avatar,
	)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileOfficial = `-- name: UpdateProfileOfficial :one
UPDATE profiles
SET official = $2, updated_at = NOW()
WHERE account_id = $1
RETURNING account_id, username, official, pseudonym, description, avatar, created_at, updated_at
`

type UpdateProfileOfficialParams struct {
	AccountID uuid.UUID
	Official  bool
}

func (q *Queries) UpdateProfileOfficial(ctx context.Context, arg UpdateProfileOfficialParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileOfficial, arg.AccountID, arg.Official)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileUsername = `-- name: UpdateProfileUsername :one
UPDATE profiles
SET username = $2, updated_at = NOW()
WHERE account_id = $1
RETURNING account_id, username, official, pseudonym, description, avatar, created_at, updated_at
`

type UpdateProfileUsernameParams struct {
	AccountID uuid.UUID
	Username  string
}

func (q *Queries) UpdateProfileUsername(ctx context.Context, arg UpdateProfileUsernameParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileUsername, arg.AccountID, arg.Username)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.Official,
		&i.Pseudonym,
		&i.Description,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
