openapi: 3.0.0
info:
  title: Chains lab profile service
  description: profile service docs
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateProfile:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  description: Username
    UpdateProfile:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              properties:
                pseudonym:
                  type: string
                  description: Pseudonym
                description:
                  type: string
                  description: Description
                avatar:
                  type: string
                  format: uri
                  description: Avatar URL
                sex:
                  type: string
                  description: sex prikin'
                birthdate:
                  type: string
                  format: date-time
                  description: Birthday
    UpdateUsername:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  description: Username
    UpdateBirthDate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              required:
                - birth_date
              properties:
                birth_date:
                  type: string
                  format: date-time
                  description: birth date user
                  pattern: DD-MM-YYYY
    UpdateSex:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              required:
                - sex
              properties:
                sex:
                  type: string
                  description: sex
    UpdateOfficial:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: user id
            type:
              type: string
              enum:
                - profile
            attributes:
              type: object
              required:
                - official
              properties:
                official:
                  type: boolean
                  description: official
    Profile:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/ProfileData'
    ProfileData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: user id
        type:
          type: string
          enum:
            - profile
        attributes:
          $ref: '#/components/schemas/ProfileAttributes'
    ProfileAttributes:
      type: object
      required:
        - username
        - official
        - updated_at
        - created_at
      properties:
        username:
          type: string
          description: Username
        pseudonym:
          type: string
          description: Pseudonym
        description:
          type: string
          description: Description
        avatar:
          type: string
          format: uri
          description: Avatar URL
        official:
          type: boolean
          description: Is Official Account
        sex:
          type: string
          description: sex prikin'
        birthdate:
          type: string
          format: date-time
          description: Birthday
        updated_at:
          type: string
          format: date-time
          description: Updated At
        created_at:
          type: string
          format: date-time
          description: Created At
    ProfilesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProfileData'
        links:
          type: object
          required:
            - page_number
            - page_size
            - total_items
          properties:
            page_number:
              type: integer
              format: int64
              description: The current page number.
              example: 1
            page_size:
              type: integer
              format: int64
              description: The number of items per page.
              example: 10
            total_items:
              type: integer
              format: int64
              description: The total number of items available.
              example: 100
