openapi: 3.0.0
info:
  title: Chains lab profile service
  description: profile service docs
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    #requests
    CreateProfile:
      $ref: './spec/components/schemas/CreateProfile.yaml'
    UpdateProfile:
      $ref: './spec/components/schemas/UpdateProfile.yaml'
    UpdateUsername:
      $ref: './spec/components/schemas/UpdateUsername.yaml'
    UpdateBirthDate:
      $ref: './spec/components/schemas/UpdateBirthDate.yaml'
    UpdateSex:
      $ref: './spec/components/schemas/UpdateSex.yaml'
    UpdateOfficial:
      $ref: './spec/components/schemas/UpdateOfficial.yaml'

    #responses
    Profile:
        $ref: './spec/components/schemas/Profile.yaml'
    ProfileData:
      $ref: './spec/components/schemas/ProfileData.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/ProfileAttributes.yaml'

